/**
 * Chord label → guitar chord shapes (all positions).
 *
 * chordl produces chord symbols like "Am", "G7", "Cmaj7", "F#m7b5"; this maps
 * them to shapes and returns every position, so callers can offer alternate
 * fret placements. Unknown chords return null — shapes are never invented.
 *
 * Three sources feed this, and a caller should not have to know which one
 * answered:
 *
 *   1. hand-authored top-3-string presets (the `guitar-top3` instrument),
 *   2. chords-db, for the instruments that have a library,
 *   3. generated power chords, which chords-db cannot carry — it has no "5"
 *      suffix — but which are perfectly regular and so need no curation.
 *
 * All three emit through `dbPositionToChord`, so renderers see one contract.
 */
// Generated by scripts/build-data.mjs from @tombatossals/chords-db (MIT), with
// the unused midi/capo position fields stripped — see that script for why.
import guitarDb from "./generated/guitar.slim.json" with { type: "json" };
import ukuleleDb from "./generated/ukulele.slim.json" with { type: "json" };
import type { Chord } from "svguitar";
import {
  INSTRUMENTS,
  dbPositionToChord,
} from "./instruments.js";
import type {
  ChordsDb,
  ChordsDbEntry,
  ChordsDbPosition,
  InstrumentId,
} from "./instruments.js";
import { rootPitchClass } from "./pitch.js";
import { splitLabel, toDbSuffix } from "./chordNames.js";
import { powerChordPosition } from "./powerChords.js";
import type { PowerChordStringSet } from "./powerChords.js";
import { findTop3Preset } from "./staticPresets.js";
import type { StaticPreset } from "./staticPresets.js";
import { positionFacts } from "./voicingFacts.js";
import { levelForFacts } from "./experience.js";
import type { ExperienceLevel } from "./experience.js";

const GUITAR_DB = guitarDb as unknown as ChordsDb;
const UKULELE_DB = ukuleleDb as unknown as ChordsDb;

// chords-db ships guitar and ukulele voicing libraries.
function dbFor(instrument: InstrumentId): ChordsDb | null {
  if (instrument === "guitar") return GUITAR_DB;
  if (instrument === "ukulele") return UKULELE_DB;
  return null;
}

// chordl roots → candidate chords-db root keys, most-likely first. chords-db
// spells accidentals inconsistently across instruments (guitar uses "Csharp"/
// "Fsharp"; ukulele uses "Db"/"Gb"), so each accidental lists both spellings
// and findEntry picks whichever the active library actually has.
const ROOT_TO_DB_KEYS: Record<string, string[]> = {
  C: ["C"], "B#": ["C"],
  "C#": ["Csharp", "Db"], Db: ["Db", "Csharp"],
  D: ["D"],
  "D#": ["Eb", "Dsharp"], Eb: ["Eb", "Dsharp"],
  E: ["E"], Fb: ["E"],
  F: ["F"], "E#": ["F"],
  "F#": ["Fsharp", "Gb"], Gb: ["Gb", "Fsharp"],
  G: ["G"],
  "G#": ["Ab", "Gsharp"], Ab: ["Ab", "Gsharp"],
  A: ["A"],
  "A#": ["Bb", "Asharp"], Bb: ["Bb", "Asharp"],
  B: ["B"], Cb: ["B"],
};

function findEntry(db: ChordsDb, label: string): ChordsDbEntry | null {
  const parsed = splitLabel(label);
  if (!parsed) return null;
  const candidates = ROOT_TO_DB_KEYS[parsed.root];
  if (!candidates) return null;
  const dbSuffix = toDbSuffix(parsed.suffix);
  // Pick the root spelling this library actually uses (guitar vs ukulele
  // differ). Prefer a spelling that carries the requested suffix: no root is
  // currently listed under both spellings, but chords-db is a floating
  // dependency and picking purely by presence would hide the other spelling.
  const spellings = candidates.map((k) => db.chords[k]).filter(Boolean);
  const entries =
    spellings.find((e) => e.some((x) => x.suffix === dbSuffix)) ?? spellings[0];
  if (!entries) return null;
  return entries.find((e) => e.suffix === dbSuffix) ?? null;
}

// ── Power chords ────────────────────────────────────────────────────────────

/** Root on the 6th string, then on the 5th — two real placements, not two spellings. */
const POWER_STRING_SETS: PowerChordStringSet[] = ["E", "A"];

/**
 * A bare fifth: root + fifth, no third. `D5` is the common spelling; the parser
 * also produces it for "D power chord" style input, so matching the resolved
 * suffix here (rather than the raw text) covers every route in.
 */
function isFifth(suffix: string): boolean {
  return suffix.trim() === "5";
}

function powerChordPositions(label: string): ChordsDbPosition[] {
  const pc = rootPitchClass(label);
  if (pc == null) return [];
  return POWER_STRING_SETS
    .map((stringSet) => powerChordPosition(pc, { stringSet }))
    .filter((p): p is ChordsDbPosition => p !== null);
}

// ── Top-3-string presets ────────────────────────────────────────────────────

/**
 * Presets are authored as svguitar shapes, but callers expect chords-db-style
 * positions (that is what carries `baseFret` for the "fret N" caption). Convert
 * back: svguitar numbers strings high-to-low from 1, positions run low-to-high.
 *
 * The window is already decided — `toPreset` put it on `chord.position`, so
 * every consumer of the preset table sees the same one — and `chord` frets are
 * relative to it, which is exactly what `baseFret` means. So there is nothing to
 * recompute here, only to rename.
 */
function presetToPosition(preset: StaticPreset): ChordsDbPosition {
  const frets = new Array<number>(6).fill(-1);
  const fingers = new Array<number>(6).fill(0);
  for (const f of preset.chord.fingers) {
    const [stringNo, fret, label] = f as [number, number | string, string?];
    const idx = 6 - stringNo;
    if (idx < 0 || idx > 5) continue;
    if (fret === "x") { frets[idx] = -1; continue; }
    frets[idx] = typeof fret === "number" ? fret : -1;
    const n = Number(label);
    fingers[idx] = Number.isFinite(n) ? n : 0;
  }
  return { frets, fingers, baseFret: preset.chord.position ?? 1, barres: [] };
}

/**
 * The table resolves both halves of the label itself — root by pitch class, and
 * suffix through the same `toDbSuffix` the six-string path uses — so there is
 * nothing to translate here beyond finding where the root stops.
 *
 * A miss still returns null. Falling back to a six-string shape under a
 * three-string label would be a lie.
 */
function findPreset(label: string): StaticPreset | null {
  const parsed = splitLabel(label);
  return parsed ? findTop3Preset(parsed.root, parsed.suffix) : null;
}

export interface GuitarChordResult {
  /** The chord label as given. */
  label: string;
  instrument: InstrumentId;
  /** Raw chords-db positions (low→high frets, baseFret, barres, fingers). */
  positions: ChordsDbPosition[];
  /** svguitar Chord objects, one per position, ready to render. */
  shapes: Chord[];
  /** How hard each shape is to play, parallel to `positions`/`shapes`. */
  levels: ExperienceLevel[];
}

/**
 * Look up all stored shapes for a chord label. Returns null when the chord or
 * instrument isn't supported.
 */
export function lookupGuitarChord(
  label: string,
  instrument: InstrumentId = "guitar",
): GuitarChordResult | null {
  const strings = INSTRUMENTS[instrument]?.strings;
  if (strings == null) return null;
  const openMidi = INSTRUMENTS[instrument].openMidi;
  const rootPc = rootPitchClass(label);
  // chords-db and generated positions have no stored level: derive it from the
  // same facts levelForFacts always ranks on.
  const derivedLevels = (positions: ChordsDbPosition[]): ExperienceLevel[] =>
    positions.map((pos) => levelForFacts(positionFacts(pos, openMidi, rootPc)));
  const toResult = (
    positions: ChordsDbPosition[],
    levels: ExperienceLevel[] = derivedLevels(positions),
  ): GuitarChordResult | null =>
    positions.length === 0
      ? null
      : {
          label,
          instrument,
          positions,
          shapes: positions.map((pos) => dbPositionToChord(pos, strings, label)),
          levels,
        };

  // 1. Hand-authored beats generated: the preset table is the only source of
  //    three-string voicings, and it does not fall back to chords-db. Its
  //    level is precomputed and stored on the preset — see src/experience.ts.
  if (instrument === "guitar-top3") {
    const preset = findPreset(label);
    return preset ? toResult([presetToPosition(preset)], [preset.level]) : null;
  }

  // 2. chords-db, for the instruments that ship a library.
  const db = dbFor(instrument);
  const entry = db ? findEntry(db, label) : null;
  if (entry && entry.positions.length > 0) return toResult(entry.positions);

  // 3. Power chords, which chords-db has no suffix for. Guitar only — a
  //    reentrant ukulele tuning makes root+fifth a different problem.
  const parsed = splitLabel(label);
  if (instrument === "guitar" && parsed && isFifth(parsed.suffix)) {
    return toResult(powerChordPositions(label));
  }

  return null;
}

/** True when at least one shape exists for the label. */
export function hasGuitarChord(label: string, instrument: InstrumentId = "guitar"): boolean {
  return lookupGuitarChord(label, instrument) !== null;
}
