/**
 * Chord label → guitar chord shapes (all positions).
 *
 * chordl produces chord symbols like "Am", "G7", "Cmaj7", "F#m7b5"; this maps
 * them to shapes and returns every position, so callers can offer alternate
 * fret placements. Unknown chords return null — shapes are never invented.
 *
 * Three sources feed this, and a caller should not have to know which one
 * answered:
 *
 *   1. hand-authored top-3-string presets (the `guitar-top3` instrument),
 *   2. chords-db, for the instruments that have a library,
 *   3. generated power chords, which chords-db cannot carry — it has no "5"
 *      suffix — but which are perfectly regular and so need no curation.
 *
 * All three emit through `dbPositionToChord`, so renderers see one contract.
 */
// Generated by scripts/build-data.mjs from @tombatossals/chords-db (MIT), with
// the unused midi/capo position fields stripped — see that script for why.
import guitarDb from "./generated/guitar.slim.json" with { type: "json" };
import ukuleleDb from "./generated/ukulele.slim.json" with { type: "json" };
import type { Chord } from "svguitar";
import {
  INSTRUMENTS,
  dbPositionToChord,
} from "./instruments.js";
import type {
  ChordsDb,
  ChordsDbEntry,
  ChordsDbPosition,
  InstrumentId,
} from "./instruments.js";
import { rootPitchClass } from "./pitch.js";
import { powerChordPosition } from "./powerChords.js";
import type { PowerChordStringSet } from "./powerChords.js";
import { GUITAR_TOP3_PRESETS } from "./staticPresets.js";
import type { StaticPreset } from "./staticPresets.js";

const GUITAR_DB = guitarDb as unknown as ChordsDb;
const UKULELE_DB = ukuleleDb as unknown as ChordsDb;

// chords-db ships guitar and ukulele voicing libraries.
function dbFor(instrument: InstrumentId): ChordsDb | null {
  if (instrument === "guitar") return GUITAR_DB;
  if (instrument === "ukulele") return UKULELE_DB;
  return null;
}

// chordl roots → candidate chords-db root keys, most-likely first. chords-db
// spells accidentals inconsistently across instruments (guitar uses "Csharp"/
// "Fsharp"; ukulele uses "Db"/"Gb"), so each accidental lists both spellings
// and findEntry picks whichever the active library actually has.
const ROOT_TO_DB_KEYS: Record<string, string[]> = {
  C: ["C"], "B#": ["C"],
  "C#": ["Csharp", "Db"], Db: ["Db", "Csharp"],
  D: ["D"],
  "D#": ["Eb", "Dsharp"], Eb: ["Eb", "Dsharp"],
  E: ["E"], Fb: ["E"],
  F: ["F"], "E#": ["F"],
  "F#": ["Fsharp", "Gb"], Gb: ["Gb", "Fsharp"],
  G: ["G"],
  "G#": ["Ab", "Gsharp"], Ab: ["Ab", "Gsharp"],
  A: ["A"],
  "A#": ["Bb", "Asharp"], Bb: ["Bb", "Asharp"],
  B: ["B"], Cb: ["B"],
};

// chordl suffix → chords-db suffix. Most match verbatim; only the triads and a
// couple of aliases need translating.
function toDbSuffix(suffix: string): string {
  const s = suffix.trim();
  if (s === "" || s === "maj" || s === "M") return "major";
  if (s === "m" || s === "min" || s === "-") return "minor";
  if (s === "min7") return "m7";
  if (s === "M7") return "maj7";
  if (s === "°") return "dim";
  if (s === "°7") return "dim7";
  if (s === "ø" || s === "ø7") return "m7b5";
  // chords-db spells the 6/9 voicings without the slash.
  if (s === "6/9") return "69";
  if (s === "m6/9") return "m69";
  // Bare "sus" (and "7sus") carry no extension number; sus4 is the convention.
  if (s === "sus") return "sus4";
  if (s === "7sus") return "7sus4";
  return s; // m7, maj7, 7, dim7, sus4, 6, 9, 11, 13, m7b5, ... match verbatim
}

function splitLabel(label: string): { root: string; suffix: string } | null {
  const m = label.trim().match(/^([A-Ga-g][#b]?)(.*)$/);
  if (!m) return null;
  const root = m[1].charAt(0).toUpperCase() + m[1].slice(1);
  return { root, suffix: m[2] };
}

function findEntry(db: ChordsDb, label: string): ChordsDbEntry | null {
  const parsed = splitLabel(label);
  if (!parsed) return null;
  const candidates = ROOT_TO_DB_KEYS[parsed.root];
  if (!candidates) return null;
  const dbSuffix = toDbSuffix(parsed.suffix);
  // Pick the root spelling this library actually uses (guitar vs ukulele
  // differ). Prefer a spelling that carries the requested suffix: no root is
  // currently listed under both spellings, but chords-db is a floating
  // dependency and picking purely by presence would hide the other spelling.
  const spellings = candidates.map((k) => db.chords[k]).filter(Boolean);
  const entries =
    spellings.find((e) => e.some((x) => x.suffix === dbSuffix)) ?? spellings[0];
  if (!entries) return null;
  return entries.find((e) => e.suffix === dbSuffix) ?? null;
}

// ── Power chords ────────────────────────────────────────────────────────────

/** Root on the 6th string, then on the 5th — two real placements, not two spellings. */
const POWER_STRING_SETS: PowerChordStringSet[] = ["E", "A"];

/**
 * A bare fifth: root + fifth, no third. `D5` is the common spelling; the parser
 * also produces it for "D power chord" style input, so matching the resolved
 * suffix here (rather than the raw text) covers every route in.
 */
function isFifth(suffix: string): boolean {
  return suffix.trim() === "5";
}

function powerChordPositions(label: string): ChordsDbPosition[] {
  const pc = rootPitchClass(label);
  if (pc == null) return [];
  return POWER_STRING_SETS
    .map((stringSet) => powerChordPosition(pc, { stringSet }))
    .filter((p): p is ChordsDbPosition => p !== null);
}

// ── Top-3-string presets ────────────────────────────────────────────────────

/**
 * The preset table spells qualities in words where chords-db uses symbols, so a
 * chordl label has to be translated before lookup. Only the suffixes the table
 * actually carries are mapped; anything else finds nothing, which is correct —
 * falling back to a six-string shape under a three-string label would be a lie.
 */
function toPresetSuffix(suffix: string): string {
  const s = suffix.trim();
  if (s === "") return "major";
  if (s === "m" || s === "min") return "minor";
  return s; // 7, m7, maj7 match the table verbatim
}

/**
 * Presets are authored as svguitar shapes, but callers expect chords-db-style
 * positions (that is what carries `baseFret` for the "fret N" caption). Convert
 * back: svguitar numbers strings high-to-low from 1, positions run low-to-high.
 *
 * Preset frets are absolute, measured from the nut. chords-db positions are not:
 * a value f > 0 sounds at `baseFret - 1 + f`, so a window that does not start at
 * the nut needs its frets rewritten relative to it. Which window depends on the
 * shape:
 *
 *   - everything within the drawn window (`INSTRUMENTS[...].frets`) stays at the
 *     nut, `baseFret: 1`, absolute frets — this is every first-position shape,
 *     and every open string lives here;
 *   - anything higher slides: `baseFret` is the shape's lowest fretted fret, and
 *     each fret becomes `f - baseFret + 1`.
 *
 * -1 (muted) and 0 (open) are sentinels and are never offset. A slid window has
 * no open strings to offset anyway — the generator will not emit a shape that
 * mixes one with a note past the window, because no window could show both.
 */
function presetToPosition(preset: StaticPreset, instrument: InstrumentId): ChordsDbPosition {
  const frets = new Array<number>(6).fill(-1);
  const fingers = new Array<number>(6).fill(0);
  for (const f of preset.chord.fingers) {
    const [stringNo, fret, label] = f as [number, number | string, string?];
    const idx = 6 - stringNo;
    if (idx < 0 || idx > 5) continue;
    if (fret === "x") { frets[idx] = -1; continue; }
    frets[idx] = typeof fret === "number" ? fret : -1;
    const n = Number(label);
    fingers[idx] = Number.isFinite(n) ? n : 0;
  }

  const fretted = frets.filter((f) => f > 0);
  const highest = fretted.length ? Math.max(...fretted) : 0;
  if (highest <= INSTRUMENTS[instrument].frets) {
    return { frets, fingers, baseFret: 1, barres: [] };
  }

  const baseFret = Math.min(...fretted);
  return {
    frets: frets.map((f) => (f > 0 ? f - baseFret + 1 : f)),
    fingers,
    baseFret,
    barres: [],
  };
}

function findPreset(label: string): StaticPreset | null {
  const parsed = splitLabel(label);
  if (!parsed) return null;
  const suffix = toPresetSuffix(parsed.suffix);
  return (
    GUITAR_TOP3_PRESETS.find((p) => p.key === parsed.root && p.suffix === suffix) ?? null
  );
}

export interface GuitarChordResult {
  /** The chord label as given. */
  label: string;
  instrument: InstrumentId;
  /** Raw chords-db positions (low→high frets, baseFret, barres, fingers). */
  positions: ChordsDbPosition[];
  /** svguitar Chord objects, one per position, ready to render. */
  shapes: Chord[];
}

/**
 * Look up all stored shapes for a chord label. Returns null when the chord or
 * instrument isn't supported.
 */
export function lookupGuitarChord(
  label: string,
  instrument: InstrumentId = "guitar",
): GuitarChordResult | null {
  const strings = INSTRUMENTS[instrument]?.strings;
  if (strings == null) return null;
  const toResult = (positions: ChordsDbPosition[]): GuitarChordResult | null =>
    positions.length === 0
      ? null
      : {
          label,
          instrument,
          positions,
          shapes: positions.map((pos) => dbPositionToChord(pos, strings, label)),
        };

  // 1. Hand-authored beats generated: the preset table is the only source of
  //    three-string voicings, and it does not fall back to chords-db.
  if (instrument === "guitar-top3") {
    const preset = findPreset(label);
    return preset ? toResult([presetToPosition(preset, instrument)]) : null;
  }

  // 2. chords-db, for the instruments that ship a library.
  const db = dbFor(instrument);
  const entry = db ? findEntry(db, label) : null;
  if (entry && entry.positions.length > 0) return toResult(entry.positions);

  // 3. Power chords, which chords-db has no suffix for. Guitar only — a
  //    reentrant ukulele tuning makes root+fifth a different problem.
  const parsed = splitLabel(label);
  if (instrument === "guitar" && parsed && isFifth(parsed.suffix)) {
    return toResult(powerChordPositions(label));
  }

  return null;
}

/** True when at least one shape exists for the label. */
export function hasGuitarChord(label: string, instrument: InstrumentId = "guitar"): boolean {
  return lookupGuitarChord(label, instrument) !== null;
}
